controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - rail_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_finger_joint1
initial:  # Define initial robot poses.
  - group: arm
    pose: ready
  - group: hand
    pose: ready2